language: go

go:
  - "1.13"

env:
  - IMAGE_NAME=mellanox/k8s-rdma-shared-dev-plugin

go:
  - 1.13.x

before_script:
  - go get -u github.com/mattn/goveralls
  - sudo apt-get update -qq
  - sudo apt-get install hwdata -yq

script:
  - make lint
  - make test-coverage
  - goveralls -coverprofile=k8s-rdma-shared-dev-plugin.cover -service=travis-ci
  - make build
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh $IMAGE_NAME latest $TRAVIS_CPU_ARCH
    on:
      branch: master
  # Push image to Dockerhub on tag
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh $IMAGE_NAME $TRAVIS_TAG $TRAVIS_CPU_ARCH
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
