language: go
sudo: required

before_script:
  - go get github.com/mattn/goveralls

script:

  - make lint
  - sudo -E env "PATH=$PATH" make test
  - sudo -E env "PATH=$PATH" make test-coverage
  - for pkg in `ls test/coverage/*.cover`; do goveralls -coverprofile=$pkg -service=travis-ci; done
  - make build
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: >
     bash -c '
     docker push $IMAGE_NAME;
     echo done'
    on:
      branch: master