# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=v1.16.1"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "v1.4.7"

[[constraint]]
  name = "github.com/Mellanox/rdmamap"
  revision = "7c3c4763a6ee6a4d624fe133135dc3a7c483111c"
  source = "https://github.com/Mellanox/rdmamap.git"

[[override]]
  name = "github.com/vishvananda/netlink"
  revision = "ed8931371a8063912d9cf485a35447e791ee6f83"
  source = "https://github.com/vishvananda/netlink.git"

[[override]]
  name = "github.com/vishvananda/netns"
  revision = "0a2b9b5464df8343199164a0321edf3313202f7e"
  source = "https://github.com/vishvananda/netns.git"

[[override]]
  name = "golang.org/x/sys"
  source = "https://github.com/golang/sys.git"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"