name: "Build"
on: [push, pull_request]


permissions:
  contents: read

jobs:
  ci:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-ci-reusable.yml@main
    with:
      test-command: make test-coverage
      apt-packages: hwdata
