name: License Check

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  call-license-check:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/license-check-reusable.yml@main