name: go-static-analysis
on: [push, pull_request]

permissions:
  contents: read

jobs:
  hadolint:
    uses: Mellanox/cloud-orchestration-reusable-workflows/.github/workflows/go-check-reusable.yml@main
    with:
      command: make hadolint
